# -*- coding: utf-8 -*-
# 生成繁体中文(zh-Hant，台湾/香港术语惯例)资源文件
import re

T = {
 "ActionGroup_HDR":"HDR",
 "Actions":"動作",
 "ActionShortcuts":"快捷動作",
 "ActionType":"類型",
 "Action_HDRSwitch":"設定 HDR",
 "ActivateHDR":"啟用 HDR",
 "Add":"新增",
 "AllDisplays":"所有顯示器",
 "AlreadyRunning":"AutoActions 已在執行。",
 "AppClosedActions":"應用程式關閉時的動作",
 "AppFocusedActions":"應用程式取得焦點時的動作",
 "Application":"應用程式",
 "ApplicationAction":"應用程式動作",
 "ApplicationName":"應用程式名稱",
 "Applications":"應用程式",
 "AppLostFocusActions":"應用程式失去焦點時的動作",
 "AppStartedActions":"應用程式啟動時的動作",
 "Arguments":"參數",
 "AudioAction":"音訊",
 "AutoActions":"AutoActions",
 "AutoActionsToolTip":"根據執行中的應用程式在此顯示器上啟用 HDR",
 "AutoStart":"開機自動啟動",
 "AutoUpdate":"自動更新",
 "BuyBeer":"請我喝杯啤酒!",
 "ChangeColorDepth":"變更色彩深度",
 "ChangeHDR":"變更 HDR",
 "Changelog":"更新記錄",
 "ChangePlaybackDevice":"變更播放裝置",
 "ChangeRecordDevice":"變更錄音裝置",
 "ChangeRefreshRate":"變更更新率",
 "ChangeResolution":"變更解析度",
 "CheckForNewVersion":"啟動時檢查新版本",
 "ChooseApplication":"選擇應用程式",
 "ChooseUWPApplication":"選擇 UWP 應用程式...",
 "Close":"關閉",
 "CloseProgramAction":"關閉程式",
 "ColorDepth":"色彩深度 [位元]",
 "ColorDepth.BPC10":"10 位元",
 "ColorDepth.BPC12":"12 位元",
 "ColorDepth.BPC16":"16 位元",
 "ColorDepth.BPC6":"6 位元",
 "ColorDepth.BPC8":"8 位元",
 "ColorDepth.BPCUnkown":"-",
 "CompatibilityModeToolTip":"在首次出現時重新啟動該應用程式，因為部分應用程式需要在啟動前就已啟用 HDR。",
 "CreateLogFile":"建立記錄檔",
 "CurrentApplication":"目前應用程式",
 "CurrentProfile":"目前設定檔:",
 "DeactivateHDR":"停用 HDR",
 "DefaultProfile":"預設設定檔",
 "DeviceID":"裝置 ID",
 "DeviceUID":"UID",
 "Display":"顯示器",
 "DisplayAction":"顯示器動作",
 "DisplayName":"顯示器名稱",
 "Displays":"顯示器",
 "Download":"從 GitHub 下載",
 "DownloadNewestVersion":"下載",
 "Edit":"編輯",
 "Error":"錯誤",
 "ExceptionRestartProcess":"重新啟動應用程式失敗。",
 "FilePath":"檔案路徑",
 "ForceKill":"強制關閉",
 "GitHub":"GitHub",
 "GlobalAutoHDR":"對所有顯示器使用自動 HDR 模式",
 "GraphicsCard":"顯示卡",
 "HDR":"HDR",
 "HDRMode":"自動 HDR 模式",
 "HideSplashScreenOnStartup":"啟動時隱藏啟動畫面",
 "HideSplashScreenOnUpdate":"更新時隱藏啟動畫面",
 "Icon":"圖示",
 "Info":"資訊",
 "IsPrimaryMonitor":"主要顯示器",
 "LastActions":"最近動作",
 "LaunchApplication":"啟動應用程式",
 "License":"授權條款",
 "Local":"本機",
 "Logging":"記錄",
 "Logs":"記錄",
 "ManagedHDR":"自動 HDR 模式",
 "MessageInvalidSettings":"設定無效。",
 "MessageMissingAudioDevice":"缺少音訊裝置。",
 "MessageMissingFile":"缺少檔案。",
 "MessageMissingProcessName":"缺少處理程序名稱。",
 "MessageReferenceLoop":"被參照的設定檔形成了迴圈。",
 "MessageReferenceProfileNotFound":"找不到 Guid 為 {0} 的被參照設定檔。",
 "MinimizeToTray":"關閉時最小化至系統匣",
 "Monitors":"顯示器",
 "Name":"名稱",
 "No":"否",
 "NoApplication":"沒有正在執行的應用程式",
 "NoProfile":"未指派設定檔",
 "OK":"確定",
 "Online":"線上",
 "Open":"開啟",
 "Priority":"優先順序",
 "ProcessName":"處理程序名稱",
 "Profile":"設定檔",
 "Profiles":"設定檔",
 "ReferenceProfileAction":"參照設定檔",
 "RefreshRate":"更新率 [Hz]",
 "ReleaseDate":"發行日期",
 "RemoveApplication":"移除",
 "RemoveProfile":"移除",
 "Resolution":"解析度",
 "RestartProccessOnFirstOccurence":"重新啟動應用程式",
 "RunAction":"執行",
 "RunProgramAction":"執行程式",
 "Save":"儲存",
 "Settings":"設定",
 "Shutdown":"結束應用程式",
 "StartToTray":"啟動時最小化至系統匣",
 "Status":"狀態",
 "Updating":"正在更新 AutoActions...",
 "Version":"版本",
 "VolumeSyncDevices":"音量同步裝置",
 "WaitForProgramEnd":"等待程式結束",
 "Yes":"是",
}
print("total:", len(T))

def gen(src, dst):
    txt = open(src, encoding='utf-8-sig').read()
    src_keys = set(re.findall(r'<data name="([^"]+)" xml:space="preserve">', txt))
    def repl(m):
        name, attrs = m.group(1), m.group(2)
        if name in T:
            return f'<data name="{name}"{attrs}><value>{T[name]}</value>'
        return m.group(0)
    out = re.sub(r'<data name="([^"]+)"( xml:space="preserve")>\s*<value>(.*?)</value>',
                 repl, txt, flags=re.S)
    hdr = '<!-- Traditional Chinese (zh-Hant) localization. Added by Squarelan on 2026-07-21. Original (C) Heiko Thome / Codectory, GNU GPL v3. -->'
    out = out.replace('<root>', hdr + '\n<root>', 1)
    open(dst, 'w', encoding='utf-8-sig').write(out)
    missing = [k for k in src_keys if k not in T]
    print(f"{dst}: keys={len(src_keys)} translated={len(src_keys)-len(missing)} missing={missing}")

gen("Source/AutoActions.ProjectResources/ProjectLocales.resx",
    "Source/AutoActions.ProjectResources/ProjectLocales.zh-Hant.resx")
gen("Source/AutoActions.Displays/Locale.resx",
    "Source/AutoActions.Displays/Locale.zh-Hant.resx")
